export interface ExamPreset {
  id: string;
  name: string;
  shortName: string;
  category: 'SSC' | 'UPSC' | 'NTA' | 'Banking' | 'Railways' | 'Defence' | 'State PSC' | 'Citizen' | 'Custom';
  type: 'photo' | 'signature' | 'thumb' | 'declaration' | 'postcard';
  width_px: number;
  height_px: number;
  width_cm: number;
  height_cm: number;
  dpi: number;
  min_kb: number;
  max_kb: number;
  target_kb: number;
  format: 'image/jpeg' | 'image/png';
  requires_name_date: boolean;
  name_date_mandatory?: boolean;
  background_rule: string;
  guidelines: string[];
  popular?: boolean;
  slug?: string;
}

export const EXAM_PRESETS: ExamPreset[] = [
  // --- SSC ---
  {
    id: 'ssc_cgl_photo',
    name: 'SSC CGL / CHSL / MTS Photo',
    shortName: 'SSC Photo',
    category: 'SSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: true,
    background_rule: 'White or clear light background, both ears visible',
    guidelines: [
      'Dimensions: 3.5 cm (width) x 4.5 cm (height) [350x450 px]',
      'File size strictly between 20.0 KB and 50.0 KB',
      'Format: JPEG / JPG only',
      'Spectacles / caps / masks are NOT allowed',
      'Name & Date of Photo (DOP) printed at bottom recommended for SSC forms'
    ],
    popular: true,
    slug: 'ssc-photo-resizer'
  },
  {
    id: 'ssc_cgl_signature',
    name: 'SSC Signature (CGL/CHSL/MTS/GD)',
    shortName: 'SSC Signature',
    category: 'SSC',
    type: 'signature',
    width_px: 400,
    height_px: 200,
    width_cm: 4.0,
    height_cm: 2.0,
    dpi: 300,
    min_kb: 10,
    max_kb: 20,
    target_kb: 15,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White paper with clear dark black ink',
    guidelines: [
      'Dimensions: 4.0 cm (width) x 2.0 cm (height) [400x200 px]',
      'File size strictly between 10.0 KB and 20.0 KB',
      'Sign in running handwriting (ALL CAPS signature will be rejected)',
      'Black ink on crisp white paper'
    ],
    popular: true,
    slug: 'ssc-signature-resize'
  },
  {
    id: 'ssc_gd_photo',
    name: 'SSC GD Constable Photo',
    shortName: 'SSC GD Photo',
    category: 'SSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: true,
    background_rule: 'White or plain light background',
    guidelines: [
      'Size: 20 KB to 50 KB',
      '3.5 x 4.5 cm portrait view',
      'Clear frontal face without headgear'
    ],
    popular: true
  },
  {
    id: 'ssc_cpo_photo',
    name: 'SSC CPO / Stenographer Photo',
    shortName: 'SSC CPO Photo',
    category: 'SSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: true,
    background_rule: 'White background',
    guidelines: ['20-50 KB range', '350x450 px']
  },

  // --- UPSC ---
  {
    id: 'upsc_ias_photo',
    name: 'UPSC Civil Services (IAS/IPS/NDA/CDS) Photo',
    shortName: 'UPSC Photo',
    category: 'UPSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 300,
    target_kb: 100,
    format: 'image/jpeg',
    requires_name_date: true,
    name_date_mandatory: true,
    background_rule: 'Plain white background mandatory',
    guidelines: [
      'Dimensions: 350x450 px (min 350x350 to max 1000x1000 px)',
      'File size: 20 KB to 300 KB',
      'Must contain Candidate Name and Date of Photo (taken within 10 days of notification)',
      'Face should occupy 3/4th of the photo'
    ],
    popular: true,
    slug: 'upsc-photo-resize'
  },
  {
    id: 'upsc_signature',
    name: 'UPSC Signature (OTR / Civil Services / NDA)',
    shortName: 'UPSC Signature',
    category: 'UPSC',
    type: 'signature',
    width_px: 400,
    height_px: 200,
    width_cm: 4.0,
    height_cm: 2.0,
    dpi: 300,
    min_kb: 20,
    max_kb: 300,
    target_kb: 80,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Clean white background with black/blue pen',
    guidelines: [
      'Dimensions: 400x200 px (350x350 to 1000x1000 px supported)',
      'File size: 20 KB to 300 KB',
      'Sign with dark pen on white paper'
    ],
    popular: true,
    slug: 'upsc-signature-resize'
  },

  // --- NTA ---
  {
    id: 'nta_neet_passport_photo',
    name: 'NTA NEET UG Passport Photo',
    shortName: 'NEET Passport Photo',
    category: 'NTA',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 200,
    target_kb: 50,
    format: 'image/jpeg',
    requires_name_date: true,
    name_date_mandatory: true,
    background_rule: 'Strictly white background, 80% face coverage with ears visible',
    guidelines: [
      'File size: 10 KB to 200 KB',
      'Dimensions: 3.5 x 4.5 cm (350x450 px)',
      'Mandatory: Candidate Name and Date of Taking Photograph',
      'White background with 80% face coverage'
    ],
    popular: true,
    slug: 'nta-neet-photo-compress'
  },
  {
    id: 'nta_neet_postcard_photo',
    name: 'NTA NEET UG Postcard Photo (4x6 inch)',
    shortName: 'NEET Postcard Photo',
    category: 'NTA',
    type: 'postcard',
    width_px: 600,
    height_px: 900,
    width_cm: 10.16,
    height_cm: 15.24,
    dpi: 300,
    min_kb: 10,
    max_kb: 200,
    target_kb: 120,
    format: 'image/jpeg',
    requires_name_date: true,
    name_date_mandatory: true,
    background_rule: 'Strictly white background (4x6 inch aspect ratio)',
    guidelines: [
      'Postcard size (4" x 6" ratio)',
      'File size: 10 KB to 200 KB',
      'Name of candidate and date of photograph at bottom'
    ],
    popular: true
  },
  {
    id: 'nta_neet_signature',
    name: 'NTA NEET / JEE Signature',
    shortName: 'NEET/JEE Signature',
    category: 'NTA',
    type: 'signature',
    width_px: 350,
    height_px: 150,
    width_cm: 3.5,
    height_cm: 1.5,
    dpi: 300,
    min_kb: 4,
    max_kb: 30,
    target_kb: 18,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background with black ballpoint pen',
    guidelines: [
      'File size strictly: 4 KB to 30 KB',
      'Dimensions: 3.5 x 1.5 cm',
      'Running handwriting only'
    ],
    popular: true
  },
  {
    id: 'nta_jee_photo',
    name: 'JEE Main / Advanced Photo',
    shortName: 'JEE Main Photo',
    category: 'NTA',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 200,
    target_kb: 60,
    format: 'image/jpeg',
    requires_name_date: true,
    background_rule: 'White background, clear view',
    guidelines: ['10 KB to 200 KB', 'JPEG format']
  },
  {
    id: 'nta_cuet_photo',
    name: 'CUET UG / PG Photo',
    shortName: 'CUET Photo',
    category: 'NTA',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 200,
    target_kb: 50,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background',
    guidelines: ['10 KB to 200 KB', '3.5 x 4.5 cm']
  },

  // --- Banking & Insurance ---
  {
    id: 'ibps_po_photo',
    name: 'IBPS PO / Clerk / RRB Photo',
    shortName: 'IBPS Photo',
    category: 'Banking',
    type: 'photo',
    width_px: 200,
    height_px: 230,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 200,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Light coloured or white background',
    guidelines: [
      'Dimensions: 200 x 230 pixels (preferred)',
      'File size: 20 KB to 50 KB',
      'No red-eye, cap, dark glasses'
    ],
    popular: true,
    slug: 'ibps-photo-signature'
  },
  {
    id: 'ibps_signature',
    name: 'IBPS Signature (PO/Clerk/SO)',
    shortName: 'IBPS Signature',
    category: 'Banking',
    type: 'signature',
    width_px: 140,
    height_px: 60,
    width_cm: 3.5,
    height_cm: 1.5,
    dpi: 200,
    min_kb: 10,
    max_kb: 20,
    target_kb: 15,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White paper with black ink pen',
    guidelines: [
      'Dimensions: 140 x 60 pixels',
      'File size: 10 KB to 20 KB',
      'Signature in CAPITAL LETTERS will NOT be accepted'
    ],
    popular: true
  },
  {
    id: 'ibps_thumb',
    name: 'IBPS Left Thumb Impression',
    shortName: 'IBPS Thumb',
    category: 'Banking',
    type: 'thumb',
    width_px: 240,
    height_px: 240,
    width_cm: 3.0,
    height_cm: 3.0,
    dpi: 200,
    min_kb: 20,
    max_kb: 50,
    target_kb: 30,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White paper with blue or black ink stamp',
    guidelines: ['Dimensions: 240 x 240 pixels (3x3 cm)', 'File size: 20 KB to 50 KB']
  },
  {
    id: 'ibps_declaration',
    name: 'IBPS Hand Written Declaration',
    shortName: 'IBPS Declaration',
    category: 'Banking',
    type: 'declaration',
    width_px: 800,
    height_px: 400,
    width_cm: 10.0,
    height_cm: 5.0,
    dpi: 200,
    min_kb: 50,
    max_kb: 100,
    target_kb: 75,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White paper written in English with black ink',
    guidelines: [
      'Dimensions: 800 x 400 pixels (10x5 cm)',
      'File size: 50 KB to 100 KB',
      'Written in running handwriting in English'
    ]
  },
  {
    id: 'sbi_po_photo',
    name: 'SBI PO / Clerk Photo',
    shortName: 'SBI Photo',
    category: 'Banking',
    type: 'photo',
    width_px: 200,
    height_px: 230,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 200,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White or light background',
    guidelines: ['20-50 KB range', '200x230 px']
  },
  {
    id: 'rbi_grade_b_photo',
    name: 'RBI Grade B / Assistant Photo',
    shortName: 'RBI Photo',
    category: 'Banking',
    type: 'photo',
    width_px: 200,
    height_px: 230,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 200,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background',
    guidelines: ['20-50 KB', '200x230 px']
  },

  // --- Railways ---
  {
    id: 'rrb_ntpc_photo',
    name: 'RRB NTPC / Group D / ALP Photo',
    shortName: 'RRB Photo',
    category: 'Railways',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Light / white plain background',
    guidelines: [
      'Dimensions: 35mm x 45mm (350x450 px)',
      'File size: 20 KB to 50 KB',
      'Recent color passport photo'
    ],
    popular: true
  },
  {
    id: 'rrb_signature',
    name: 'RRB Signature (NTPC/Group D/ALP)',
    shortName: 'RRB Signature',
    category: 'Railways',
    type: 'signature',
    width_px: 500,
    height_px: 200,
    width_cm: 5.0,
    height_cm: 2.0,
    dpi: 300,
    min_kb: 10,
    max_kb: 40,
    target_kb: 25,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White paper with black ink',
    guidelines: ['Dimensions: 50mm x 20mm', 'File size: 10 KB to 40 KB']
  },

  // --- Defence & Police ---
  {
    id: 'airforce_agniveer_photo',
    name: 'Indian Air Force Agniveer Photo (With Slate)',
    shortName: 'IAF Agniveer Photo',
    category: 'Defence',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 50,
    target_kb: 30,
    format: 'image/jpeg',
    requires_name_date: true,
    background_rule: 'Light background holding black slate with Name & Date in chalk',
    guidelines: [
      'Candidate holding black slate in front of chest',
      'Name and Date of Photo clearly written with chalk',
      'File size: 10 KB to 50 KB'
    ]
  },
  {
    id: 'army_agniveer_photo',
    name: 'Indian Army Agniveer Rally Photo',
    shortName: 'Army Photo',
    category: 'Defence',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 20,
    target_kb: 15,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background, standard haircut and clean shaved',
    guidelines: ['Strict 10 KB to 20 KB limit for Army rally portal']
  },
  {
    id: 'navy_agniveer_photo',
    name: 'Indian Navy Agniveer SSR / MR Photo',
    shortName: 'Navy Photo',
    category: 'Defence',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Blue or plain light background',
    guidelines: ['20-50 KB range']
  },

  // --- State PSCs ---
  {
    id: 'uppsc_photo',
    name: 'UPPSC (Uttar Pradesh PSC) Photo',
    shortName: 'UPPSC Photo',
    category: 'State PSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: true,
    background_rule: 'White or light grey background',
    guidelines: ['20-50 KB limit', '3.5x4.5 cm']
  },
  {
    id: 'bpsc_photo',
    name: 'BPSC (Bihar PSC) Photo',
    shortName: 'BPSC Photo',
    category: 'State PSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 15,
    max_kb: 25,
    target_kb: 20,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background',
    guidelines: ['Strict 15 KB to 25 KB range for BPSC online']
  },
  {
    id: 'bpsc_signature',
    name: 'BPSC Signature (Hindi & English)',
    shortName: 'BPSC Signature',
    category: 'State PSC',
    type: 'signature',
    width_px: 350,
    height_px: 150,
    width_cm: 3.5,
    height_cm: 1.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 20,
    target_kb: 15,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White paper with black ink',
    guidelines: ['10-20 KB range']
  },
  {
    id: 'mpsc_photo',
    name: 'MPSC (Maharashtra PSC) Photo',
    shortName: 'MPSC Photo',
    category: 'State PSC',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White or off-white background',
    guidelines: ['20-50 KB', 'JPEG format']
  },
  {
    id: 'kerala_psc_photo',
    name: 'Kerala PSC Photo (with Name & Date Footer)',
    shortName: 'Kerala PSC Photo',
    category: 'State PSC',
    type: 'photo',
    width_px: 150,
    height_px: 200,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 200,
    min_kb: 10,
    max_kb: 30,
    target_kb: 22,
    format: 'image/jpeg',
    requires_name_date: true,
    name_date_mandatory: true,
    background_rule: 'White background with printed Name and Date in white bottom section',
    guidelines: [
      'Dimensions: 150 x 200 pixels',
      'File size: 10 KB to 30 KB max',
      'Name of candidate and date of photo mandatory in bottom strip'
    ]
  },
  {
    id: 'dsssb_postcard_photo',
    name: 'Delhi DSSSB Postcard Photo (5x7 inch)',
    shortName: 'DSSSB Postcard',
    category: 'State PSC',
    type: 'postcard',
    width_px: 500,
    height_px: 700,
    width_cm: 12.7,
    height_cm: 17.78,
    dpi: 300,
    min_kb: 50,
    max_kb: 300,
    target_kb: 150,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background showing upper body up to waist',
    guidelines: ['Postcard 5x7 inch ratio (500x700 px)', 'Size: 50 KB to 300 KB']
  },

  // --- Citizen Portals ---
  {
    id: 'passport_seva_photo',
    name: 'Passport Seva Kendra Photo (India)',
    shortName: 'Passport Photo',
    category: 'Citizen',
    type: 'photo',
    width_px: 413,
    height_px: 531,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 200,
    target_kb: 80,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Strict pure white background, 70-80% face coverage',
    guidelines: [
      'Dimensions: 3.5 cm x 4.5 cm (413x531 px at 300 DPI)',
      'File size: 20 KB to 200 KB',
      'Neutral expression, mouth closed, both ears clearly visible'
    ],
    popular: true
  },
  {
    id: 'pan_card_photo',
    name: 'PAN Card Photo (NSDL / UTIITSL)',
    shortName: 'PAN Photo',
    category: 'Citizen',
    type: 'photo',
    width_px: 213,
    height_px: 213,
    width_cm: 2.5,
    height_cm: 2.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 30,
    target_kb: 20,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background, 213x213 pixels square',
    guidelines: [
      'Exact 213 x 213 pixels (300 DPI)',
      'File size strictly max 30 KB (10-30 KB)',
      'Clear passport picture'
    ],
    popular: true
  },
  {
    id: 'pan_card_signature',
    name: 'PAN Card Signature (NSDL / UTIITSL)',
    shortName: 'PAN Signature',
    category: 'Citizen',
    type: 'signature',
    width_px: 400,
    height_px: 200,
    width_cm: 4.0,
    height_cm: 2.0,
    dpi: 300,
    min_kb: 10,
    max_kb: 30,
    target_kb: 20,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'White background with dark black ink',
    guidelines: ['Max 30 KB file size', 'Sign on plain paper']
  },
  {
    id: 'driving_license_photo',
    name: 'Driving License Photo (Sarathi Parivahan)',
    shortName: 'Sarathi DL Photo',
    category: 'Citizen',
    type: 'photo',
    width_px: 420,
    height_px: 525,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 10,
    max_kb: 20,
    target_kb: 15,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Plain light background',
    guidelines: ['Strictly 10 KB to 20 KB for Sarathi upload']
  },
  {
    id: 'driving_license_signature',
    name: 'Driving License Signature (Sarathi)',
    shortName: 'Sarathi DL Sign',
    category: 'Citizen',
    type: 'signature',
    width_px: 256,
    height_px: 128,
    width_cm: 4.0,
    height_cm: 2.0,
    dpi: 300,
    min_kb: 10,
    max_kb: 20,
    target_kb: 15,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Black ink signature',
    guidelines: ['Strictly 10 KB to 20 KB']
  },

  // --- Custom ---
  {
    id: 'custom_preset',
    name: 'Custom Dimension & KB Compression',
    shortName: 'Custom Mode',
    category: 'Custom',
    type: 'photo',
    width_px: 350,
    height_px: 450,
    width_cm: 3.5,
    height_cm: 4.5,
    dpi: 300,
    min_kb: 20,
    max_kb: 50,
    target_kb: 35,
    format: 'image/jpeg',
    requires_name_date: false,
    background_rule: 'Custom configuration',
    guidelines: ['Manually set pixel width/height or cm/mm, DPI, and exact KB bounds']
  }
];

export const CATEGORIES = [
  'All',
  'SSC',
  'UPSC',
  'NTA',
  'Banking',
  'Railways',
  'Defence',
  'State PSC',
  'Citizen'
] as const;

export function getPresetById(id: string): ExamPreset {
  return EXAM_PRESETS.find(p => p.id === id) || EXAM_PRESETS[0];
}

export function getPresetBySlug(slug: string): ExamPreset | undefined {
  return EXAM_PRESETS.find(p => p.slug === slug);
}
